#!/usr/bin/env python


import argparse
from pipeline.osm_pipeline import OsmPipeline


def read_args() -> object:
    parser = argparse.ArgumentParser(description="SwayRider source data pipeline")
    parser.add_argument(
            "--config",
            default="config/config.yml",
            help="Path to the config file")
    parser.add_argument(
            "--clean",
            action="store_true",
            help="Clean this pipeline's own temp and result data before running")
    parser.add_argument(
            "--clean-all",
            action="store_true",
            help="Clean all pipeline directories before running")
    parser.add_argument(
            "--tag",
            default="",
            help="Version tag (default: current date YYYY-MM-DD)")

    args = parser.parse_args()
    return args


def main():
    args = read_args()
    pl = OsmPipeline(args)

    if not pl.initialize():
        print("Failed to initialize source data pipeline")
        return

    if not pl.run():
        print("Failed to run source data pipeline")
        return

    print("Source data pipeline completed successfully")


if __name__ == "__main__":
    main()
