#!/usr/bin/env python


import argparse
from pipeline import Publish


def read_args() -> object:
    parser = argparse.ArgumentParser(description="data publisher")
    parser.add_argument(
            "--config",
            default="config/config.yml",
            help="Path to the config file")
    parser.add_argument(
            "--manifest",
            default="manifest-data.yml",
            help="Manifest filename to publish (default: manifest-data.yml)")

    args = parser.parse_args()
    return args


def main():
    args = read_args()
    publish = Publish(args)
    if not publish.run():
        print("Failed to publish")
        return
    print("Publish completed successfully")


if __name__ == '__main__':
    main()
